In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, SimpleRNN, Dense

In [2]:
sentences = [
 "The app works perfectly",
 "I really like the new update",
 "Customer support was very helpful",
 "The design looks beautiful",
 "Everything works smoothly",
 "I had a wonderful time using this",
 "The performance is impressive",
 "Very easy to use and understand",
 "I am happy with the purchase",
 "The experience was delightful",
 "This tool saved me a lot of time",
 "Excellent quality product",
 "The interface is clean and modern",
 "I would happily use this again",
 "Superb work by the developers",

 "The app crashes too often",
 "I did not like the update",
 "Customer support ignored my issue",
 "The design looks outdated",
 "Everything feels buggy",
 "I had a terrible time using this",
 "The performance is disappointing",
 "Very confusing and hard to use",
 "I regret buying this product",
 "The experience was frustrating",
 "This tool wasted my time",
 "Poor quality product",
 "The interface is messy",
 "I will never use this again",
 "Worst service I have ever seen"
]
labels = [1]*15 + [0]*15
labels = np.array(labels)

In [3]:
vocab_size = 2000
tok  = Tokenizer(num_words = vocab_size,oov_token = "<OOV>")
tok.fit_on_texts(sentences)
seqs = tok.texts_to_sequences(sentences)
maxlen = max(len(s) for s in seqs)
X = pad_sequences(seqs,maxlen = maxlen,padding = 'post')
y = labels

In [4]:
X[0]
X[1]

array([ 3, 33, 15,  2, 34, 16,  0,  0])

In [5]:
embed_dim = 16
rnn_units = 8
# units in hidden layer

In [6]:
inp = Input(shape= (maxlen,),dtype="int32",name = 'input')
x = Embedding(input_dim=vocab_size,output_dim=embed_dim,mask_zero=True,name = 'embed')(inp)
rnn = SimpleRNN(units = rnn_units, return_sequences = False,return_state= False,name = 'simple_rnn')
x_last = rnn(x)
out = Dense(1,activation='sigmoid',name = 'out')(x_last)
model = Model(inputs =inp,outputs = out)
model.compile(optimizer='adam',loss = 'binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)  │ (None, 8)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embed (Embedding)   │ (None, 8, 16)     │     32,000 │ input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ not_equal           │ (None, 8)         │          0 │ input[0][0]       │
│ (NotEqual)          │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ simple_rnn          │ (None, 8)         │        200 │ embed[0][0],      │
│ (SimpleRNN)         │                   │            │ not_equal[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ out (Dense)         │ (None, 1)         │          9 │ simple_rnn[0][0]  │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 32,209 (125.82 KB)

 Trainable params: 32,209 (125.82 KB)

 Non-trainable params: 0 (0.00 B)

In [7]:
model.fit(X,y,epochs= 25,batch_size = 8,verbose = 1)

Epoch 1/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - accuracy: 0.5083 - loss: 0.6863
Epoch 2/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6575 - loss: 0.6728
Epoch 3/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6925 - loss: 0.6660
Epoch 4/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8117 - loss: 0.6430
Epoch 5/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7992 - loss: 0.6438
Epoch 6/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8500 - loss: 0.6216
Epoch 7/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8225 - loss: 0.6166
Epoch 8/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9275 - loss: 0.5974 
Epoch 9/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9192 - loss: 0.5674
Epoch 10/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9192 - loss: 0.5689
Epoch 11/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9067 - loss: 0.5467
Epoch 12/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9067 - loss: 0.5198
E

# Task
Create an intermediate Keras model to visualize the outputs of the embedding layer and the hidden states of the SimpleRNN layer from the existing model. Then, use this intermediate model to predict on the input data and visualize the outputs.

## Create intermediate model

### Subtask:
Build a new Keras `Model` that takes the same input as the original model but outputs the embedding layer and the hidden states of the SimpleRNN layer.


**Reasoning**:
Define an intermediate Keras model with the same input as the original model and outputs from the embedding and simple RNN layers.



In [8]:
intermediate_model = Model(inputs=model.inputs, outputs=[model.get_layer('embed').output, model.get_layer('simple_rnn').output])

In [9]:
from tensorflow.keras.layers import SimpleRNN as SRNN
seq_inp = Input(shape=(maxlen,), dtype='int32')
seq_emb = model.get_layer('embed')(seq_inp)  # reuse trained embedding

# Create RNN with return_sequences=True
rnn_seq = SRNN(units=rnn_units, return_sequences=True, name='rnn_seq')

# DO NOT CALL build() manually
seq_hidden = rnn_seq(seq_emb)  # builds automatically

# Copy trained RNN weights
try:
    trained_weights = model.get_layer('simple_rnn').get_weights()
    rnn_seq.set_weights(trained_weights)
    print("Copied RNN weights into sequence-inspection RNN.")
except Exception as e:
    print("Could not copy weights automatically:", e)

inspect_model = Model(inputs=seq_inp, outputs=seq_hidden)

# Inspect
idx = 0
example_seq = X[idx:idx+1]  # shape (1, maxlen)
hidden_seq = inspect_model.predict(example_seq)

print("Sentence:", sentences[idx])
print("Token ids:", example_seq)
print("Hidden states per timestep shape:", hidden_seq.shape)
print("Hidden states (timesteps x units):")
print(np.round(hidden_seq[0], 3))


Copied RNN weights into sequence-inspection RNN.


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step
Sentence: The app works perfectly
Token ids: [[ 2 13 14 32  0  0  0  0]]
Hidden states per timestep shape: (1, 8, 8)
Hidden states (timesteps x units):
[[ 0.003  0.001 -0.048 -0.091  0.014  0.023 -0.035  0.059]
 [ 0.062 -0.159 -0.111  0.16  -0.203 -0.074  0.155 -0.219]
 [-0.159  0.308 -0.073 -0.555  0.386 -0.219 -0.344  0.22 ]
 [ 0.538 -0.602 -0.583  0.606 -0.57   0.178  0.272  0.083]
 [ 0.538 -0.602 -0.583  0.606 -0.57   0.178  0.272  0.083]
 [ 0.538 -0.602 -0.583  0.606 -0.57   0.178  0.272  0.083]
 [ 0.538 -0.602 -0.583  0.606 -0.57   0.178  0.272  0.083]
 [ 0.538 -0.602 -0.583  0.606 -0.57   0.178  0.272  0.083]]
